api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /



app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
    
login:
    pattern:   /login
    defaults:  { _controller: ApiBundle:Seguridad:login }
    
login_check:
    pattern:   /login_checkt    
