security:

    
    providers:
        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
                    

    firewalls:
        
        default:
            anonymous: ~
            http_basic: ~
            
     #   secured_area:
     #       pattern:    ^/
     #       anonymous:  ~
     #       form_login:
     #           login_path:  login
     #           check_path:  login_check    
    
    access_control:
        - { path: /soap/*, roles: ROLE_ADMIN }
    
    
    

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext